### ISSUE TITLE
Math Question

### ISSUE THREAD

**Issue by ngocuong0105** [LateGenXer/finance#2]
Hey thank you for building this investment tool. it is very useful!

I wonder can you explain the maths behind computing the median winnings on premium bonds? I believe it is on this 79 line in `nsandi_premium_bonds.py`:

https://github.com/LateGenXer/finance/blob/f7c7c097f37a8dd4acd42966ea8e0c5625c80ba3/nsandi_premium_bonds.py#L79

I see that you use binomial distribution and do some kind of convolution?

**Comment by LateGenXer** [comment]
First I use the Binomial distribution to give a probability of receiving a given prize _n_ times.   The probability of receiving a prize £X in a single prize draw is exactly once is our number of bonds over total number of draws.  But for every £X prize there are multiple draws, and Binomial will give the probability of receiving it _n_ times of those draws.


Then I use convolution to combine the probabilities across different prizes values.  For example, the probability of receiving £100 after £25 and £50 prizes is the sum of the probabilities of:
- receiving £0 on the first prize and 2x£50 on the second
- receiving 2x£25 and £50 on both prizes
- receiving 4x£35 on the first prize and £0 on the second

And this works out to be a convolution in practice.  See for example https://stats.stackexchange.com/questions/331973/why-is-the-sum-of-two-random-variables-a-convolution

Though one can't just use `numpy.convolve` because padding/alignment is different.)

Initially I used more extensive scalar math, but using numpy arrays allows to compute the probabilities faster and more succinctly.

So think about this way:
- Binomial distribution gives the probability distribution function of the a single price winnings
- convolution of the PDFs gives the probability distribution function of sum of all price winnings
only that instead of continual PDFs we have discrete probabilities across multiples of £25 as a numpy vector.   (The right term is Probability Mass Function.)

Getting the median after knowing the probability function is just a matter of computing the cumulative probabilities and finding the value at 50%.


I hope this makes it clearer.

You asked just out of curiosity, or with a specific need in mind?

**Comment by ngocuong0105** [comment]
No specific need - was just curious. Thanks for the quick response!

**Comment by LateGenXer** [comment]
No problem.  I'm happy to oblige.

I added better code comments in 031f865ae9fda6099327971b4464a5587094ba3e
