### ISSUE TITLE
UF1 not getting to zero

### ISSUE THREAD

**Issue by thisiscristo** [LateGenXer/finance#3]
Hey
Firstly - thank you so much for the calculator. It's amazing.
Can you please help me answer this....
When I plug in my numbers and set Retirement Income to 0 (maximum) it still leaves my UF1 with a healthy amount and it forecasts me being left with £2.5m. Is my understanding of that right? Anyway I can alter this calculation so the UF1 gets used up a bit more? Or is it already used and I am misunderstanding it...!?
Thanks

[rtp-2024-09-25-10_47_18+00_00.json](https://github.com/user-attachments/files/17129701/rtp-2024-09-25-10_47_18%2B00_00.json)

**Comment by LateGenXer** [comment]
The problem is that there aren't enough funds on the ISA to sustain higher spending until pension can be accessed.

The calculator could use different retirement income figures pre/post- pension access, but that's not how it's designed.

You need to reduce your pension yearly contribution, and increase the GIA/ISA yearly contribution to even out things if you want to retire this early.

**Comment by thisiscristo** [comment]
thanks for coming back to me so quickly, I'll have a play around.
